@startuml

start
:Опрос группировки МРК //(1)//;
:Формирование группы МРК для исследования //(2)//;
if (Удалось сформировать группу?) then (нет)
 :Сообщить о невозможности создания группы //(3)//;
 stop
else (да)
endif
:Формирование плана движения для каждого МРК //(4)//;
if (Удалось найти путь к объекту?) then (нет)
 :Сообщить об отсутствии пути //(5)//;
else (да)
endif
stop

@enduml