@startuml
start
:Получение запроса //(1)//;
:Построение плана исследования //(2)//;
:Рассылка команд на исследование другим МРК //(3)//;
if (Робот присутствует в плане?) then (да)
while (Все точки исследованы?) is (нет)
:Движение к очередной точке //(4)//;
:Выполнение исследований //(5)//;
:Сохранение результатов //(6)//;
endwhile (да)
else (нет)
endif
stop
@enduml