@startuml

|СУСТЗ|
start
:Формирование направлений съемки //(1)//;
repeat
:Запрос на поворот камеры //(2)//;
|Подвес камеры|
:Поворот камеры //(3)//;
|СУСТЗ|
:Запрос на съемку //(4)//;
|Подвес камеры|
:Выполнение съемки //(5)//;
|Экспертная система СТЗ|
:Распознавание объектов //(6)//;
|СУСТЗ|
:Сохранение результатов //(7)//;
repeat while (все направления отсняты?)
stop

@enduml