@startuml

actor "Внешняя система"
boundary "Ведущая СУТЗ"

"Внешняя система" -> "Ведущая СУТЗ" : Запрос на исследование



"Ведущая СУТЗ" -> "Подчиненная СУТЗ" : Опрос состояния
"Подчиненная СУТЗ" --> "Ведущая СУТЗ" : Статус
"Ведущая СУТЗ" -> "Ведущая СУТЗ" : Формирование группы МРК
"Ведущая СУТЗ" -> "СПМиУД" : Запрос на\nпостроение маршрутов
"СПМиУД" --> "Ведущая СУТЗ" : План движения группы МРК
"Ведущая СУТЗ" -> "Подчиненная СУТЗ" : Рассылка планов движения
"Подчиненная СУТЗ" -> "Подчиненная СУТЗ" : Выполнение плана\nисследования
"Ведущая СУТЗ" --> "Внешняя система" : Статус и \nплан исследования
"Ведущая СУТЗ" -> "Ведущая СУТЗ" : Выполнение плана\nисследования

database "РСУБД"

"Ведущая СУТЗ" -> "РСУБД" : Сохранение результатов
"Подчиненная СУТЗ" -> "РСУБД" : Сохранение результатов
"Подчиненная СУТЗ" -> "Ведущая СУТЗ" : Сообщение о\nвыполнении плана

@enduml